# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('metadata', jsonfield.fields.JSONField()),
                ('data', models.BinaryField(null=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='schedule.ScheduleEntry')),
            ],
            options={
                'db_table': 'acquisitions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together=set([('schedule_entry', 'task_id')]),
        ),
    ]
