# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('sigmf_metadata', jsonfield.fields.JSONField()),
                ('data', models.BinaryField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
                'db_table': 'acquisitions',
            },
        ),
    ]
