# Generated by Django 2.2.1 on 2019-05-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisitions', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='schedule_entry',
            field=models.ForeignKey(help_text='The schedule entry relative to the acquisition', on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='schedule.ScheduleEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together={('schedule_entry', 'task_id', 'recording_id')},
        ),
    ]
