# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_auto_20170822_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text=b'The time the acquisition was created'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='data',
            field=models.BinaryField(help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='schedule_entry',
            field=models.ForeignKey(help_text=b'The schedule entry relative to the acquisition', on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='schedule.ScheduleEntry'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='sigmf_metadata',
            field=jsonfield.fields.JSONField(help_text=b'The sigmf meta data for the acquisition'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='task_id',
            field=models.IntegerField(help_text=b'The id of the task relative to the acquisition'),
        ),
    ]
