# Generated by Django 2.2 on 2019-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190507_2008'),
        ('acquisitions', '0002_auto_20190330_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='recording_id',
            field=models.IntegerField(default=0, help_text='The id of the recording relative to the task'),
        ),
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together={('schedule_entry', 'task_id', 'recording_id')},
        ),
    ]
