# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=5, help_text=b'Longitude of the sensor in decimal degrees.', max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=5, help_text=b'Longitude of the sensor in decimal degrees.', max_digits=8)),
            ],
        ),
    ]
