# Generated by Django 2.2.13 on 2020-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gps",
                    models.BooleanField(
                        help_text="Identifies this as autogenerated location information"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Time of last location update."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Display this location on /status."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Freeform text description of this location.",
                        max_length=1024,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude of the sensor in decimal degrees.",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude of the sensor in decimal degrees.",
                        max_digits=9,
                    ),
                ),
            ],
        ),
    ]
