# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', models.BooleanField(help_text=b'Identifies this as autogenerated location information')),
                ('modified', models.DateTimeField(auto_now=True, help_text=b'Time of last location update.')),
                ('active', models.BooleanField(default=True, help_text=b'Display this location on /status.')),
                ('description', models.CharField(blank=True, help_text=b'Freeform text description of this location.', max_length=1024)),
                ('latitude', models.DecimalField(decimal_places=6, help_text=b'Longitude of the sensor in decimal degrees.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text=b'Longitude of the sensor in decimal degrees.', max_digits=9)),
            ],
        ),
    ]
