# Generated by Django 3.0.14 on 2021-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='height',
            field=models.DecimalField(decimal_places=3, help_text='Height of the sensor in meters above sea level.', max_digits=9, null=True),
        ),
    ]
