# Generated by Django 3.2.18 on 2023-05-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0003_auto_20211217_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Latitude of the sensor in decimal degrees (WGS84).",
                max_digits=9,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Longitude of the sensor in decimal degrees (WGS84).",
                max_digits=9,
            ),
        ),
    ]
