ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   build-essential zlib1g-dev libncurses5-dev \
                   libgdbm-dev libnss3-dev libssl-dev \
                   libreadline-dev libffi-dev libsqlite3-dev \
                   wget libbz2-dev \
                   libusb-1.0-0 libpython3.11 \
                   git smartmontools \
                   python3.11 python3.11-dev usbutils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.11 get-pip.py

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /src
WORKDIR /src
COPY ./src/requirements.txt /src
COPY ./src/requirements-dev.txt /src

ARG DOCKER_GIT_CREDENTIALS
RUN git config --global credential.helper store && echo "${DOCKER_GIT_CREDENTIALS}" > ~/.git-credentials
RUN python3.11 -m pip install --upgrade pip
ARG DEBUG
RUN if [ "$DEBUG" = true ]; then python3.11 -m pip install --no-cache-dir -r requirements-dev.txt ; else python3.11 -m pip install --no-cache-dir -r requirements.txt ; fi

COPY ./src /src
COPY ./gunicorn /gunicorn

RUN mkdir -p /entrypoints
COPY ./entrypoints/api_entrypoint.sh /entrypoints

RUN chmod +x /entrypoints/api_entrypoint.sh

COPY ./configs /configs

# Args are passed in via docker-compose during build time
ARG DOMAINS
ARG IPS
ARG SECRET_KEY
