FROM nginx:1.17-alpine

RUN mkdir -p /var/www/scos-sensor/static
# copy static files from api container
COPY --chown=nginx:nginx --from=smsntia/scos-sensor:latest /src/static/ /var/www/scos-sensor/static/
COPY --chown=root:root ./nginx/conf.template /etc/nginx/nginx.conf.template
