ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive \
                   apt-get install -qy --no-install-recommends \
                   git python3 libpq-dev \
		   swig gcc python3-dev \
		   libpython3-stdlib  && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt install --reinstall libpython3-stdlib

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /src
WORKDIR /src
COPY ./src/requirements.txt /src

ARG DOCKER_GIT_CREDENTIALS
RUN git config --global credential.helper store && echo "${DOCKER_GIT_CREDENTIALS}" > ~/.git-credentials
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY ./src /src
COPY ./gunicorn /gunicorn

RUN mkdir -p /entrypoints
COPY ./entrypoints/api_entrypoint.sh /entrypoints

RUN mkdir -p /scripts
COPY ./scripts/create_superuser.py /scripts

RUN chmod +x /entrypoints/api_entrypoint.sh

COPY ./configs /configs

# Args are passed in via docker-compose during build time
ARG DEBUG
ARG DOMAINS
ARG IPS
ARG SECRET_KEY
