# Generated by Django 2.2.2 on 2019-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="data",
            field=models.FileField(null=True, upload_to="blob/%Y/%m/%d/%H/%M/%S"),
        )
    ]
