# Generated by Django 3.0.4 on 2020-08-17 18:15

from django.db import migrations, models
import tasks.models.encrypted_storage


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200319_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='data',
            field=models.FileField(null=True, storage=tasks.models.encrypted_storage.EncryptedStorage(), upload_to='blob/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
