# Generated by Django 3.1.14 on 2022-01-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200319_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='data_encrypted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
