# Generated by Django 3.1 on 2020-08-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200821_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='data_encrypted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
