# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='server_url',
            field=models.URLField(blank=True, help_text=b'URL of server if account belongs to a sensor manager', null=True, verbose_name=b'Server URL'),
        ),
    ]
