# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_auto_20180219_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfpath',
            options={'ordering': ('rf_path_number',)},
        ),
    ]
