# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0003_auto_20180219_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_controller', models.CharField(blank=True, help_text=b'Description of host computer. E.g. Make, model, and configuration.', max_length=1024, null=True)),
                ('antenna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capabilities.Antenna')),
                ('data_extraction_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capabilities.DataExtractionUnit')),
                ('signal_condition_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='capabilities.SignalConditioningUnit')),
            ],
        ),
    ]
