# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0004_sensordefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='horizontal_gain_pattern',
            field=models.CharField(blank=True, help_text=b'Antenna gain pattern in horizontal plane. Enter as comma-separated floating point numbers. [dBi]', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='vertical_gain_pattern',
            field=models.CharField(blank=True, help_text=(b'Antenna gain pattern in vertical plane. [dBi]', b'Enter as comma-separated floating point numbers. [dBi]'), max_length=1023, null=True),
        ),
    ]
