# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import scheduler.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=50)),
                ('action_parameters', jsonfield.fields.JSONField(default=dict)),
                ('priority', models.SmallIntegerField(default=10)),
                ('start', models.BigIntegerField(blank=True, default=scheduler.utils.timefn)),
                ('stop', models.BigIntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('relative_stop', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False, editable=False)),
                ('next_task_id', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'db_table': 'schedule',
            },
        ),
    ]
