# Generated by Django 3.0.4 on 2020-03-18 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import schedule.models.schedule_entry


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme", models.CharField(blank=True, max_length=16, null=True)),
                ("version", models.CharField(blank=True, max_length=16, null=True)),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "name",
                    models.SlugField(
                        help_text="[Required] The unique identifier used in URLs and filenames",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[],
                        help_text="[Required] The name of the action to be scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=10,
                        help_text="Lower number is higher priority (default=10)",
                        validators=[
                            django.core.validators.MinValueValidator(-20),
                            django.core.validators.MaxValueValidator(19),
                        ],
                    ),
                ),
                (
                    "start",
                    models.BigIntegerField(
                        blank=True,
                        default=schedule.models.schedule_entry.next_schedulable_timefn,
                        help_text="Absolute time (epoch) to start, or leave blank for 'now'",
                    ),
                ),
                (
                    "stop",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Absolute time (epoch) to stop, or leave blank for 'never'",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seconds between tasks, or leave blank to run once",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the entry should be removed from the scheduler without removing it from the system",
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        blank=True,
                        help_text="If given, the scheduler will POST a `TaskResult` JSON object to this URL after each task completes",
                        null=True,
                    ),
                ),
                (
                    "next_task_time",
                    models.BigIntegerField(
                        editable=False,
                        help_text="The time the next task is scheduled to be executed",
                        null=True,
                    ),
                ),
                (
                    "next_task_id",
                    models.IntegerField(
                        default=1,
                        editable=False,
                        help_text="The id of the next task to be executed",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date the entry was created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="The date the entry was modified"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        help_text="The name of the user who owns the entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        editable=False,
                        help_text="The request that created the entry",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.Request",
                    ),
                ),
            ],
            options={"db_table": "schedule", "ordering": ("created",)},
        ),
    ]
