# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('logger', 'logger - Log the message "running test {seid}/{tid}" at log level INFO.'), ('logger2', 'logger2 - Log the message "running test {seid}/{tid}" at log level INFO.')], max_length=50)),
                ('priority', models.SmallIntegerField(default=10)),
                ('start', models.BigIntegerField(blank=True, default=schedule.models.ScheduleEntry.timefn)),
                ('stop', models.BigIntegerField(blank=True, default=None, null=True)),
                ('relative_stop', models.BooleanField(default=False)),
                ('interval', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('canceled', models.BooleanField(default=False, editable=False)),
                ('next_task_id', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ('created_at',),
            },
        ),
    ]
