# Generated by Django 3.0.4 on 2020-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='action',
            field=models.CharField(choices=[('logger', 'logger - Log the message "running test {name}/{tid}".')], help_text='[Required] The name of the action to be scheduled', max_length=50),
        ),
    ]
