# Generated by Django 2.2.13 on 2021-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleentry",
            name="action",
            field=models.CharField(
                choices=[
                    (
                        "acquire_iq_700MHz_ATT_DL",
                        "acquire_iq_700MHz_ATT_DL - Capture time-domain IQ samples at the following 1 frequencies: 739.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_ATT_UL",
                        "acquire_iq_700MHz_ATT_UL - Capture time-domain IQ samples at the following 1 frequencies: 709.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_FirstNet_DL",
                        "acquire_iq_700MHz_FirstNet_DL - Capture time-domain IQ samples at the following 1 frequencies: 763.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_FirstNet_UL",
                        "acquire_iq_700MHz_FirstNet_UL - Capture time-domain IQ samples at the following 1 frequencies: 793.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_P-SafetyNB_DL",
                        "acquire_iq_700MHz_P-SafetyNB_DL - Capture time-domain IQ samples at the following 1 frequencies: 772.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_P-SafetyNB_UL",
                        "acquire_iq_700MHz_P-SafetyNB_UL - Capture time-domain IQ samples at the following 1 frequencies: 802.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_T-Mobile_DL",
                        "acquire_iq_700MHz_T-Mobile_DL - Capture time-domain IQ samples at the following 1 frequencies: 731.50 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_T-Mobile_UL",
                        "acquire_iq_700MHz_T-Mobile_UL - Capture time-domain IQ samples at the following 1 frequencies: 700.50 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_Verizon_DL",
                        "acquire_iq_700MHz_Verizon_DL - Capture time-domain IQ samples at the following 1 frequencies: 751.00 MHz.",
                    ),
                    (
                        "acquire_iq_700MHz_Verizon_UL",
                        "acquire_iq_700MHz_Verizon_UL - Capture time-domain IQ samples at the following 1 frequencies: 782.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_ATT_DL",
                        "acquire_m4s_700MHz_ATT_DL - Apply m4s detector over 300 1024-pt FFTs at 739.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_ATT_UL",
                        "acquire_m4s_700MHz_ATT_UL - Apply m4s detector over 300 1024-pt FFTs at 709.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_FirstNet_DL",
                        "acquire_m4s_700MHz_FirstNet_DL - Apply m4s detector over 300 1024-pt FFTs at 763.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_FirstNet_UL",
                        "acquire_m4s_700MHz_FirstNet_UL - Apply m4s detector over 300 1024-pt FFTs at 793.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_P-SafetyNB_DL",
                        "acquire_m4s_700MHz_P-SafetyNB_DL - Apply m4s detector over 300 1024-pt FFTs at 772.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_P-SafetyNB_UL",
                        "acquire_m4s_700MHz_P-SafetyNB_UL - Apply m4s detector over 300 1024-pt FFTs at 802.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_T-Mobile_DL",
                        "acquire_m4s_700MHz_T-Mobile_DL - Apply m4s detector over 300 1024-pt FFTs at 731.50 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_T-Mobile_UL",
                        "acquire_m4s_700MHz_T-Mobile_UL - Apply m4s detector over 300 1024-pt FFTs at 700.50 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_Verizon_DL",
                        "acquire_m4s_700MHz_Verizon_DL - Apply m4s detector over 300 1024-pt FFTs at 751.00 MHz.",
                    ),
                    (
                        "acquire_m4s_700MHz_Verizon_UL",
                        "acquire_m4s_700MHz_Verizon_UL - Apply m4s detector over 300 1024-pt FFTs at 782.00 MHz.",
                    ),
                    ("logger", 'logger - Log the message "running test {name}/{tid}".'),
                    (
                        "monitor_usrp",
                        "monitor_usrp - Monitor USRP connection and restart container if unreachable.",
                    ),
                    (
                        "survey_700MHz_band_10dB_1000ms_iq",
                        "survey_700MHz_band_10dB_1000ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_10dB_80ms_iq",
                        "survey_700MHz_band_10dB_80ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_20dB_1000ms_iq",
                        "survey_700MHz_band_20dB_1000ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_20dB_80ms_iq",
                        "survey_700MHz_band_20dB_80ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_40dB_1000ms_iq",
                        "survey_700MHz_band_40dB_1000ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_40dB_80ms_iq",
                        "survey_700MHz_band_40dB_80ms_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "survey_700MHz_band_iq",
                        "survey_700MHz_band_iq - Capture time-domain IQ samples at the following 10 frequencies: 700.50 MHz, 709.00 MHz, 731.50 MHz, 739.00 MHz, 751.00 MHz, 763.00 MHz, 772.00 MHz, 782.00 MHz, 793.00 MHz, 802.00 MHz.",
                    ),
                    (
                        "sync_gps",
                        "sync_gps - Query the GPS and syncronize time and location.",
                    ),
                ],
                help_text="[Required] The name of the action to be scheduled",
                max_length=50,
            ),
        ),
    ]
