# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='relative_stop',
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='action',
            field=models.CharField(choices=[(b'acquire700c', b'acquire700c - Acquire 700c LTE band with m4s detector over 30 consecutive FFTs.'), (b'logger', b'logger - Log the message "running test {name}/{tid}" at log level INFO.'), (b'mock_acquire', b'mock_acquire - Test an acquisition without using the radio.')], help_text=b'action to be scheduled', max_length=50),
        ),
    ]
