# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20171104_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='action',
            field=models.CharField(choices=[(b'acquire700c', b'acquire700c - Apply m4s detector over 300 1024-point FFTs at 751.00 MHz.'), (b'logger', b'logger - Log the message "running test {name}/{tid}" at log level INFO.')], help_text=b'action to be scheduled', max_length=50),
        ),
    ]
