# Generated by Django 3.0.4 on 2020-05-08 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200501_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='interval',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds between tasks, or leave blank to run once. Must be greater than 5 for GPS sync start', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
