# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171114_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='is_private',
            field=models.BooleanField(default=False, help_text=b'deactivate an entry to remove it from the scheduler without removing it from the system'),
        ),
    ]
