# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20171115_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='action',
            field=models.CharField(choices=[(b'acquire700c', b'acquire700c - Apply m4s detector over 300 1024-point FFTs at 751.00 MHz.'), (b'logger', b'logger - Log the message "running test {name}/{tid}".')], help_text=b'The name of the action to be scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text=b'The date the entry was created'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='interval',
            field=models.PositiveIntegerField(blank=True, help_text=b'Seconds between events, or leave blank to run once', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text=b'Indicates whether the entry should be removed from the scheduler without removing it from the system'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='is_private',
            field=models.BooleanField(default=False, help_text=b'Indicates whether the entry, and resulting data, are only visible to admin'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text=b'The date the entry was modified'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='name',
            field=models.SlugField(help_text=b'The unique identifier used in URLs and filenames', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='next_task_id',
            field=models.IntegerField(default=1, editable=False, help_text=b'The id of the next task to be executed'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='next_task_time',
            field=models.BigIntegerField(editable=False, help_text=b'The time the next task is to be executed', null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='owner',
            field=models.ForeignKey(editable=False, help_text=b'The name of the user whom owns the entry', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='priority',
            field=models.SmallIntegerField(default=10, help_text=b'Lower number is higher priority (default=10)'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start',
            field=models.BigIntegerField(blank=True, default=schedule.models.next_schedulable_timefn, help_text=b"Absolute time (epoch) to start, or leave blank for 'now'"),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='stop',
            field=models.BigIntegerField(blank=True, help_text=b"Absolute time (epoch) to stop, or leave blank for 'never'", null=True),
        ),
    ]
